In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np


In [3]:
#### 2. Create a null vector of size 10 (★☆☆)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#`hint: array[4]`

array = np.zeros(10)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
matrix = np.random.randint(0,8,(3,3))
matrix

array([[3, 5, 1],
       [6, 7, 3],
       [0, 5, 5]])

In [31]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
array = [1,2,0,0,4,0]
np.nonzero(array)

(array([0, 1, 4], dtype=int64),)

In [33]:
#### 7. Create a 3x3 identity matrix (★☆☆)
#`hint: np.eye
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
np.random.random((3,3,3))    

array([[[0.34563565, 0.60221553, 0.8715144 ],
        [0.87413926, 0.96797877, 0.51406932],
        [0.86267778, 0.2793618 , 0.3165124 ]],

       [[0.02299979, 0.51656552, 0.65831352],
        [0.21422381, 0.06297125, 0.29387591],
        [0.94240217, 0.87299442, 0.9473643 ]],

       [[0.22598111, 0.27868908, 0.92248328],
        [0.98353075, 0.51417917, 0.21996728],
        [0.43233349, 0.29380357, 0.95751475]]])

In [40]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#hint: min, max`
a = np.random.random((10,10))
np.amin(a)
np.amax(a)

0.9945854243298404

In [56]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
#hint: mean`
b = np.random.random((0,30))
np.mean(b)


nan

In [13]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#hint: np.diag`

print(np.diag([1,2,3,4],k=-1)) # the code already knows that its a 5 times 5 matrix. Its is smart! And default is a zero matrix


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [105]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#hint: (x -mean)/std`
matrix3  = np.random.randint(1,8,(5,5))    
std_dev =np.std(matrix3)  
mean = np.mean(matrix3)
print(mean)
print(std_dev)
normalized_matrix = (1/std_dev)*matrix3 - (mean/std_dev)*np.eye(5,5)
print(normalized_matrix)

3.84
2.0915066339842197
[[ 0.55462411  2.39062115  3.34686961  3.34686961  0.47812423]
 [ 0.95624846 -1.35787281  1.91249692  1.43437269  1.43437269]
 [ 0.95624846  0.47812423 -0.40162435  0.95624846  0.95624846]
 [ 1.43437269  3.34686961  2.86874538 -0.87974858  0.95624846]
 [ 1.91249692  1.91249692  3.34686961  2.86874538  1.51087257]]


In [104]:
#### 13. How to find common values between two arrays? (★☆☆)
#hint: np.intersect1d`
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

In [113]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
#hint: sort`
lst = [1,2,3,10,12,0.1,4,5,6,9]
array = np.array(lst)    
np.sort(array)

array([ 0.1,  1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  9. , 10. , 12. ])

In [134]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#`hint: argmax`
lst = [1,2,3,10,12,0.1,4,5,6,9]
array1 = np.array(lst)  
array1[np.argmax(array1)] = 0
array1

array([ 1. ,  2. ,  3. , 10. ,  0. ,  0.1,  4. ,  5. ,  6. ,  9. ])

In [17]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#hint: mean(axis=,keepdims=)`
X = np.random.rand(5, 10)
print(X)
print("\n Subtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True) # axis = 1 means for each row, axis = 0 for each column


[[0.87606483 0.35601815 0.43757024 0.13051567 0.2505681  0.27883962
  0.22585433 0.12278096 0.64417373 0.04752931]
 [0.33565023 0.3455663  0.06666238 0.10990635 0.4612517  0.2815692
  0.83673308 0.95200991 0.26825194 0.35085277]
 [0.84034666 0.91954477 0.50529182 0.2520952  0.03573623 0.7577774
  0.61211648 0.36983541 0.56745602 0.64578199]
 [0.81684714 0.82181922 0.97763459 0.29112655 0.22170358 0.31642183
  0.06087393 0.20115355 0.5382091  0.00755221]
 [0.9991761  0.08401164 0.21854631 0.14796679 0.14908725 0.00225439
  0.44650066 0.02915775 0.1419119  0.46969963]]

 Subtract the mean of each row of the said matrix:



In [26]:
#### 17. How to get the n largest values of an array (★★★)
#`Z = np.arange(10000)
#np.random.shuffle(Z)
#n = 5
#hint: np.argsort | np.argpartition`
   
    
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])    

[9995 9996 9997 9998 9999]


In [143]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#`hint: np.where`
matrix5 = np.random.randint(0,8,(5,3))  
print(matrix5)
print(np.where(matrix5 >6))


[[1 0 7]
 [6 1 0]
 [1 5 7]
 [0 1 4]
 [7 4 7]]
(array([0, 2, 4, 4], dtype=int64), array([2, 2, 0, 2], dtype=int64))
