In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np


In [3]:
#### 2. Create a null vector of size 10 (★☆☆)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#`hint: array[4]`

array = np.zeros(10)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
vector = np.arange(10,49)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [30]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
matrix = np.random.randint(0,8,(3,3))
matrix

array([[5, 6, 3],
       [5, 4, 3],
       [5, 2, 3]])

In [31]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
array = [1,2,0,0,4,0]
np.nonzero(array)

(array([0, 1, 4], dtype=int64),)

In [33]:
#### 7. Create a 3x3 identity matrix (★☆☆)
#`hint: np.eye
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
np.random.random((3,3,3))    

array([[[0.34563565, 0.60221553, 0.8715144 ],
        [0.87413926, 0.96797877, 0.51406932],
        [0.86267778, 0.2793618 , 0.3165124 ]],

       [[0.02299979, 0.51656552, 0.65831352],
        [0.21422381, 0.06297125, 0.29387591],
        [0.94240217, 0.87299442, 0.9473643 ]],

       [[0.22598111, 0.27868908, 0.92248328],
        [0.98353075, 0.51417917, 0.21996728],
        [0.43233349, 0.29380357, 0.95751475]]])

In [40]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#hint: min, max`
a = np.random.random((10,10))
np.amin(a)
np.amax(a)

0.9945854243298404

In [56]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
#hint: mean`
b = np.random.random((0,30))
np.mean(b)


nan

In [126]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#hint: np.diag`
lst = [[1,2,3,10,12],[0.1,4,5,6,9],[2,7,8,9,9],[1,4,6,2,8],[5,2,9,11,3]]
matrix1 = np.array(lst)

print(np.diag(matrix1, k=-1))
print(matrix1)


matrix1[np.diag(matrix1,k=-1)] = np.array([1,2,3,4]




SyntaxError: unexpected EOF while parsing (4165689580.py, line 12)

In [105]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#hint: (x -mean)/std`
matrix3 = matrix = np.random.randint(1,8,(5,5))    
std_dev =np.std(matrix3)  
mean = np.mean(matrix3)
print(mean)
print(std_dev)
normalized_matrix = (1/std_dev)*matrix3 - (mean/std_dev)*np.eye(5,5)
print(normalized_matrix)

3.84
2.0915066339842197
[[ 0.55462411  2.39062115  3.34686961  3.34686961  0.47812423]
 [ 0.95624846 -1.35787281  1.91249692  1.43437269  1.43437269]
 [ 0.95624846  0.47812423 -0.40162435  0.95624846  0.95624846]
 [ 1.43437269  3.34686961  2.86874538 -0.87974858  0.95624846]
 [ 1.91249692  1.91249692  3.34686961  2.86874538  1.51087257]]


In [104]:
#### 13. How to find common values between two arrays? (★☆☆)
#hint: np.intersect1d`
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

In [113]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
#hint: sort`
lst = [1,2,3,10,12,0.1,4,5,6,9]
array = np.array(lst)    
np.sort(array)

array([ 0.1,  1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  9. , 10. , 12. ])

In [134]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#`hint: argmax`
lst = [1,2,3,10,12,0.1,4,5,6,9]
array1 = np.array(lst)  
array1[np.argmax(array1)] = 0
array1

array([ 1. ,  2. ,  3. , 10. ,  0. ,  0.1,  4. ,  5. ,  6. ,  9. ])

In [132]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#hint: mean(axis=,keepdims=)`
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)


[[0.59624453 0.5038728  0.77125784 0.90614173 0.49434972 0.15407008
  0.42354829 0.64489108 0.76393673 0.59368108]
 [0.70677496 0.25232528 0.36521887 0.36025166 0.16502415 0.18165122
  0.07655417 0.02297638 0.41517045 0.57078144]
 [0.19900877 0.33971797 0.92422687 0.8907326  0.87926496 0.62825479
  0.93982234 0.61226296 0.95113205 0.5807721 ]
 [0.63480092 0.94879688 0.49198191 0.29472596 0.31067256 0.39702334
  0.37982282 0.53477176 0.09090759 0.08222367]
 [0.15995638 0.04344711 0.81664488 0.75260331 0.2338316  0.35340315
  0.22706606 0.01360653 0.94591064 0.72723021]]

Subtract the mean of each row of the said matrix:



In [135]:
#### 17. How to get the n largest values of an array (★★★)
#`Z = np.arange(10000)
#np.random.shuffle(Z)
#n = 5
#hint: np.argsort | np.argpartition`
    
    
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])    

[9995 9996 9997 9998 9999]


In [140]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#`hint: np.where`
matrix5 = np.random.randint(0,8,(5,3))  
print(matrix5)
matrix5[(matrix5 > 8)] = 5


[[4 2 7]
 [5 5 1]
 [0 5 6]
 [7 7 6]
 [2 0 0]]
[[4 2 7]
 [5 5 1]
 [0 5 6]
 [7 7 6]
 [2 0 0]]
